id: I373E1F1D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:07:04+00:00'
last_modified: '2022-06-10T10:57:17.149761+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12625
  title: བྱ་ཚིག་དུས་གསུམ་གྱི་རྣམ་བཞག་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C8F5:
      image_group_id: I1KG15013
      title: ''
      total_pages: 106
      order: 1
      base_file: C8F5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
